pages with tests
dream-aim-deliver/planckster-ui-kit pull request #6
Opened 2024-03-08 10:47 UTC by harsh010102

2024-03-12 17:17 UTC, alebg commented on lib/components/card/card.styles.ts
Clean this: if useless, just delete the file

2024-03-12 17:20 UTC, alebg commented on lib/components/cardpage/cardpage.tsx
> +          <Card
Please do not hard code values, these will be provided by the backend

2024-03-12 17:33 UTC, alebg commented on lib/components/chatnavbar/Chatnavbar.tsx
For each component you push, please also provide a story, so we can also see it in the storybook

2024-03-12 17:34 UTC, alebg commented on lib/components/conversationpage/conversationpage.tsx
> +      name: "June Wildfires",
hard coded values

2024-03-12 17:34 UTC, alebg commented on lib/components/conversationpage/conversationpage.tsx
> +// import React, { useState } from 'react';
Please clean this file

2024-03-12 17:36 UTC, alebg reviewed
Please also fix the dark mode bugs

2024-03-12 17:40 UTC, alebg commented on lib/components/modal/modal.tsx
> +// // import React, { useState } from 'react';
Please also clean this

2024-03-12 17:42 UTC, alebg commented on lib/components/modal/modal.tsx
> +// Modal.tsx
Please also clean this

2024-03-12 17:47 UTC, alebg commented on lib/components/navbar/Navbar.tsx
Please generalize this to receive the page where the component is in a variable. You don't have to worry about rounting, that will be done in Websat Planckster. But we need this component to be able to receive the information of where it is as a variable, so it can decide what to highlight, etc.

2024-03-12 17:50 UTC, alebg commented on tests/components/cardpage.test.tsx
> +    expect(screen.getByText("Canada Wildfires")).toBeInTheDocument();
Adapt this test for when you take out the hard-coded values, maybe inject them as part of the test set up

2024-03-12 17:50 UTC, alebg commented on tests/components/cardpage.test.tsx
> +    expect(cards[0]).toHaveTextContent("Canada Wildfires");
Same here

2024-03-14 11:09 UTC, harsh010102 commented
previously there were lint related errors resolved it in this PR.

2024-03-14 19:39 UTC, alebg commented on stories/components/researchcontextpage.stories.ts
> +  title: "Components/researchcontextpage",
Please use consistent casing in the naming. Following your implicit criteria, this should be "ResearchContextPage"

2024-03-14 19:40 UTC, alebg commented on stories/components/conversationpage.stories.ts
> +  args: {},
You can add the hardcoded cards you had before here, as the stories won't affect the actual component. In this way, we can see test information populated. See how it's done for the "Card" component + story

2024-03-14 19:55 UTC, alebg commented on lib/components/conversationpage/conversationpage.tsx
> +        addConversation={addConversation}
This modal is not working in the story now

2024-03-14 19:58 UTC, alebg requested changes
1. Please use props in all components and wire them properly in the stories, so we can actually test your components by injecting values using Storybooks. See how it's done in the Card component.

2. NavBar is not highlighting the page where we're at

3. Create New Conversation button is not working in ConversationPage

4. Please improve the dark mode design. In the NavBar we cannot really read the name of the institute. Also, the menu items "Research Context     Conversation    About Us" do not seem very well aligned

![imagen](https://github.com/dream-aim-deliver/planckster-ui-kit/assets/62880920/a75f831f-ebec-4431-a41b-05e14b27e46f)

2024-03-14 20:04 UTC, alebg commented on lib/components/conversationpage/conversationpage.tsx
> +  const addConversation = async (name: string, description: string) => {
Remember to adapt to what I told you about the backend:

We do not have "conversation description", so your modal shouldn't contain this

2024-03-18 22:31 UTC, alebg commented
@harsh010102 I pulled from your branch but I don't see any changes, please make sure that you commited and pushed your work

2024-03-19 17:02 UTC, alebg commented
Closing because of CI breaking and git history being messed up. @harsh010102 will open a new PR

2024-03-19 17:02 UTC, closed without merging